# Generated by Django 4.2.7 on 2024-01-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfilusuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(blank=True, choices=[('cliente', 'cliente'), ('vendedor', 'vendedor')], max_length=10, null=True),
        ),
    ]
