# Generated by Django 4.2.7 on 2024-01-15 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_perfilusuario_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='alias',
        ),
    ]
