# Generated by Django 4.2.7 on 2024-01-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_perfilusuario_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='alias',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='usuario',
            field=models.CharField(max_length=50),
        ),
    ]
