# Generated by Django 4.2.7 on 2024-01-13 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='producto_asociado',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
